apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: dev project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: dev
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/**/envs/values-dev.yaml
      repoURL: https://github.com/myspotontheweb/gitops-workloads-demo.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ path[1] }}'
      name: dev-{{ path[1] }}
      namespace: argocd
    spec:
      project: dev
      destination:
        namespace: 'dev'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: https://github.com/rav17/gitops-workloads-demo.git
        path: '{{ path }}/../chart'
        targetRevision: 'main'
        helm:
          valueFiles:
            - '../chart/values.yaml'
            - '../envs/values-dev.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true