app:
  containers:
  - name: nginx  
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "300m"
      limits:
        memory: "128Mi"
        cpu: "600m"    
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 45
    readinessProbe:
      httpGet:
        path: /
        port: 80
  service:
    ports:
    - port: 80
    type: ClusterIP
