app:
  containers:
    - name: nginx
      image: nginx:1.22.0
      resources:
        requests:
          memory: "64Mi"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 45
      readinessProbe:
        httpGet:
          path: /
          port: 80
  service:
    ports:
      - port: 80
    type: ClusterIP
